"""The card tables: which cards exist, and the decks built from them."""

from typing import Callable, Dict, List, Optional, Union

from ..statuses import StatusType
from .model import (Card, CardType, TargetMode, UNPLAYABLE,
                    rarity_for_card, _BASIC_CARDS, _COMMON_CARDS,
                    _RARE_CARDS, _ANCIENT_CARDS, _TOKEN_CARDS,
                    _COLORLESS_CARDS)
from .effects import *  # noqa: F401,F403
from .effects import (_fresh_free_card, make_giant_rock,
                      _midnight_cost, _stomp_cost,
                      _clash_playable, _auto_target_for,
                      _arm_once, _arm_power, _ally_of,
                      _pick, _sample_distinct,
                      _return_next_turn, _fx_slimed)
from .tokens import *  # noqa: F401,F403
from .tokens import (_status_card, _curse, STATUS_CARDS,
                     make_wound, make_infection, make_beckon,
                     make_toxic, make_frantic_escape, make_burn,
                     make_wither, make_dazed, make_slimed)


COLORLESS_POOL: List[Callable[[], Card]] = [
    lambda: _card("Ultimate Defend", 1, CardType.SKILL, TargetMode.SELF, fx_plain_block,
                   values={"block": 11}, upgrade_values={"block": 15},
                   description="Gain 11 Block.", upgraded_description="Gain 15 Block."),
    lambda: _card("Ultimate Strike", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_plain_attack,
                   values={"damage": 14}, upgrade_values={"damage": 20},
                   description="Deal 14 damage.", upgraded_description="Deal 20 damage."),
    lambda: _card("Finesse", 0, CardType.SKILL, TargetMode.SELF, fx_finesse,
                   values={"block": 4}, upgrade_values={"block": 7},
                   description="Gain 4 Block. Draw 1 card.",
                   upgraded_description="Gain 7 Block. Draw 1 card."),
    lambda: _card("Flash of Steel", 0, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_flash_of_steel,
                   values={"damage": 5}, upgrade_values={"damage": 8},
                   description="Deal 5 damage. Draw 1 card.",
                   upgraded_description="Deal 8 damage. Draw 1 card."),
    lambda: _card("Dark Shackles", 0, CardType.SKILL, TargetMode.SINGLE_ENEMY, fx_dark_shackles,
                   values={"strength_loss": 9}, upgrade_values={"strength_loss": 15}, exhausts=True,
                   description="Enemy loses 9 Strength this turn. Exhaust.",
                   upgraded_description="Enemy loses 15 Strength this turn. Exhaust."),
    lambda: _card("Prowess", 1, CardType.POWER, TargetMode.SELF, fx_prowess,
                   values={"amount": 1}, upgrade_values={"amount": 2},
                   description="Gain 1 Strength. Gain 1 Dexterity.",
                   upgraded_description="Gain 2 Strength. Gain 2 Dexterity."),
    lambda: _card("Impatience", 0, CardType.SKILL, TargetMode.SELF, fx_impatience,
                   values={"cards": 2}, upgrade_values={"cards": 3},
                   description="If you have no Attacks in your Hand, draw 2 cards.",
                   upgraded_description="If you have no Attacks in your Hand, draw 3 cards."),
    lambda: _card("Shockwave", 2, CardType.SKILL, TargetMode.ALL_ENEMIES, fx_shockwave,
                   values={"amount": 3}, upgrade_values={"amount": 5}, exhausts=True,
                   description="Apply 3 Weak and Vulnerable to ALL enemies. Exhaust.",
                   upgraded_description="Apply 5 Weak and Vulnerable to ALL enemies. Exhaust."),
    lambda: _card("Mind Blast", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_mind_blast,
                   innate=True,
                   description="Innate. Deal damage equal to the number of cards in your Draw Pile.",
                   upgraded_description="Innate. Deal damage equal to the number of cards in your Draw Pile."),
    lambda: _card("Dramatic Entrance", 0, CardType.ATTACK, TargetMode.ALL_ENEMIES, fx_dramatic_entrance,
                   values={"damage": 11}, upgrade_values={"damage": 15},
                   innate=True, exhausts=True,
                   description="Innate. Deal 11 damage to ALL enemies. Exhaust.",
                   upgraded_description="Innate. Deal 15 damage to ALL enemies. Exhaust."),
    lambda: _card("Fisticuffs", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_fisticuffs,
                   values={"damage": 7}, upgrade_values={"damage": 9},
                   description="Deal 7 damage. Gain Block equal to damage dealt.",
                   upgraded_description="Deal 9 damage. Gain Block equal to damage dealt."),
    lambda: _card("Omnislice", 0, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_omnislice,
                   values={"damage": 8}, upgrade_values={"damage": 11},
                   description="Deal 8 damage. Damage ALL other enemies equal to the damage dealt.",
                   upgraded_description="Deal 11 damage. Damage ALL other enemies equal to the damage dealt."),
    lambda: _card("Entrench", 2, CardType.SKILL, TargetMode.SELF, fx_entrench,
                   description="Double your Block.", upgraded_description="Double your Block."),
    lambda: _card("Caltrops", 1, CardType.POWER, TargetMode.SELF, fx_caltrops,
                   values={"thorns": 3}, upgrade_values={"thorns": 5},
                   description="Whenever you are attacked, deal 3 damage back.",
                   upgraded_description="Whenever you are attacked, deal 5 damage back."),
    lambda: _card("Eternal Armor", 3, CardType.POWER, TargetMode.SELF, fx_eternal_armor,
                   values={"plating": 9}, upgrade_values={"plating": 12},
                   description="Gain 9 Plating.", upgraded_description="Gain 12 Plating."),
    lambda: _card("Rend", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_rend,
                   values={"damage": 10, "per_debuff": 5},
                   upgrade_values={"damage": 12, "per_debuff": 8},
                   description="Deal 10 damage. Deals 5 additional damage for each unique debuff on the enemy.",
                   upgraded_description="Deal 12 damage. Deals 8 additional damage for each unique debuff on the enemy."),
    lambda: _card("Master of Strategy", 0, CardType.SKILL, TargetMode.SELF, fx_master_of_strategy,
                   values={"cards": 3}, upgrade_values={"cards": 4}, exhausts=True,
                   description="Draw 3 cards. Exhaust.", upgraded_description="Draw 4 cards. Exhaust."),
    lambda: _card("Rally", 2, CardType.SKILL, TargetMode.SELF, fx_rally,
                   values={"block": 12}, upgrade_values={"block": 17},
                   description="ALL players gain 12 Block.",
                   upgraded_description="ALL players gain 17 Block."),
    lambda: _card("Beat Down", 3, CardType.SKILL, TargetMode.SELF, fx_beat_down,
                   values={"count": 3}, upgrade_values={"count": 4},
                   description="Play 3 random Attacks from your Discard Pile.",
                   upgraded_description="Play 4 random Attacks from your Discard Pile."),
    lambda: _card("Catastrophe", 2, CardType.SKILL, TargetMode.SELF, fx_catastrophe,
                   values={"count": 2}, upgrade_values={"count": 3},
                   description="Play 2 random cards from your Draw Pile.",
                   upgraded_description="Play 3 random cards from your Draw Pile."),
    lambda: _card("Secret Weapon", 0, CardType.SKILL, TargetMode.SELF, fx_secret_weapon,
                   values={"want_attack": 1}, exhausts=True,
                   description="Put an Attack from your Draw Pile into your Hand. Exhaust.",
                   upgraded_description="Put an Attack from your Draw Pile into your Hand."),
    lambda: _card("Secret Technique", 0, CardType.SKILL, TargetMode.SELF, fx_secret_weapon,
                   exhausts=True,
                   description="Put a Skill from your Draw Pile into your Hand. Exhaust.",
                   upgraded_description="Put a Skill from your Draw Pile into your Hand."),
]


COLORLESS_POOL.extend([
    lambda: _card("Automation", 1, CardType.POWER, TargetMode.SELF, fx_automation,
                   upgrade_cost=0,
                   description="Every 10 cards you draw, gain 1 Energy.",
                   upgraded_description="Every 10 cards you draw, gain 1 Energy."),
    lambda: _card("Believe in You", 0, CardType.SKILL, TargetMode.ALLY, fx_believe_in_you,
                   values={"energy": 2}, upgrade_values={"energy": 3}, is_multiplayer=True,
                   description="Another player gains 2 Energy.",
                   upgraded_description="Another player gains 3 Energy."),
    lambda: _card("Coordinate", 1, CardType.SKILL, TargetMode.ALLY, fx_coordinate,
                   values={"strength": 5}, upgrade_values={"strength": 8}, is_multiplayer=True,
                   description="Give another player 5 Strength this turn.",
                   upgraded_description="Give another player 8 Strength this turn."),
    lambda: _card("Discovery", 1, CardType.SKILL, TargetMode.SELF, fx_discovery,
                   exhausts=True, loses_exhaust_on_upgrade=True,
                   description="Choose 1 of 3 random cards to add into your Hand. It's free to play this turn. Exhaust.",
                   upgraded_description="Choose 1 of 3 random cards to add into your Hand. It's free to play this turn."),
    lambda: _card("Equilibrium", 2, CardType.SKILL, TargetMode.SELF, fx_equilibrium,
                   values={"block": 13}, upgrade_values={"block": 16},
                   description="Gain 13 Block. Retain your Hand this turn.",
                   upgraded_description="Gain 16 Block. Retain your Hand this turn."),
    lambda: _card("Fasten", 1, CardType.POWER, TargetMode.SELF, fx_fasten,
                   values={"block": 4}, upgrade_values={"block": 6},
                   description="Gain an additional 4 Block from Defend cards.",
                   upgraded_description="Gain an additional 6 Block from Defend cards."),
    lambda: _card("Gang Up", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_gang_up,
                   values={"damage": 5, "bonus": 5}, upgrade_values={"damage": 5, "bonus": 7},
                   is_multiplayer=True,
                   description="Deal 5 damage. Deals 5 additional damage for each time another player has attacked the enemy this turn.",
                   upgraded_description="Deal 5 damage. Deals 7 additional damage for each time another player has attacked the enemy this turn."),
    lambda: _card("Huddle Up", 1, CardType.SKILL, TargetMode.SELF, fx_huddle_up,
                   values={"draw": 2}, upgrade_values={"draw": 3}, exhausts=True,
                   is_multiplayer=True,
                   description="ALL allies draw 2 cards. Exhaust.",
                   upgraded_description="ALL allies draw 3 cards. Exhaust."),
    lambda: _card("Intercept", 1, CardType.SKILL, TargetMode.SELF, fx_intercept,
                   values={"block": 9}, upgrade_values={"block": 13}, is_multiplayer=True,
                   description="Gain 9 Block. Redirect all incoming attacks that would be dealt to another player this turn to you.",
                   upgraded_description="Gain 13 Block. Redirect all incoming attacks that would be dealt to another player this turn to you."),
    lambda: _card("Jack of All Trades", 0, CardType.SKILL, TargetMode.SELF, fx_jack_of_all_trades,
                   values={"count": 1}, upgrade_values={"count": 2}, exhausts=True,
                   description="Add 1 random Colorless card into your Hand. Exhaust.",
                   upgraded_description="Add 2 random Colorless cards into your Hand. Exhaust."),
    lambda: _card("Lift", 1, CardType.SKILL, TargetMode.ALLY, fx_lift,
                   values={"block": 11}, upgrade_values={"block": 16}, is_multiplayer=True,
                   description="Give another player 11 Block.",
                   upgraded_description="Give another player 16 Block."),
    lambda: _card("Panache", 0, CardType.POWER, TargetMode.SELF, fx_panache,
                   values={"damage": 10}, upgrade_values={"damage": 14},
                   description="Every time you play 5 cards in a single turn, deal 10 damage to ALL enemies.",
                   upgraded_description="Every time you play 5 cards in a single turn, deal 14 damage to ALL enemies."),
    lambda: _card("Panic Button", 0, CardType.SKILL, TargetMode.SELF, fx_panic_button,
                   values={"block": 30}, upgrade_values={"block": 40}, exhausts=True,
                   description="Gain 30 Block. You cannot gain Block from cards for 2 turns. Exhaust.",
                   upgraded_description="Gain 40 Block. You cannot gain Block from cards for 2 turns. Exhaust."),
    lambda: _card("Prep Time", 1, CardType.POWER, TargetMode.SELF, fx_prep_time,
                   values={"vigor": 4}, upgrade_values={"vigor": 6},
                   description="At the start of your turn, gain 4 Vigor.",
                   upgraded_description="At the start of your turn, gain 6 Vigor."),
    lambda: _card("Production", 0, CardType.SKILL, TargetMode.SELF, fx_plain_energy,
                   values={"energy": 2}, upgrade_values={"energy": 3}, exhausts=True,
                   description="Gain 2 Energy. Exhaust.",
                   upgraded_description="Gain 3 Energy. Exhaust."),
    lambda: _card("Prolong", 0, CardType.SKILL, TargetMode.SELF, fx_prolong,
                   exhausts=True, loses_exhaust_on_upgrade=True,
                   description="Next turn, gain Block equal to your current Block. Exhaust.",
                   upgraded_description="Next turn, gain Block equal to your current Block."),
    lambda: _card("Purity", 0, CardType.SKILL, TargetMode.SELF, fx_purity,
                   values={"count": 3}, upgrade_values={"count": 5},
                   retain=True, exhausts=True,
                   description="Retain. Exhaust up to 3 cards in your Hand. Exhaust.",
                   upgraded_description="Retain. Exhaust up to 5 cards in your Hand. Exhaust."),
    lambda: _card("Restlessness", 0, CardType.SKILL, TargetMode.SELF, fx_restlessness,
                   values={"draw": 2, "energy": 2}, upgrade_values={"draw": 3, "energy": 3},
                   retain=True,
                   description="Retain. If your Hand is empty, draw 2 cards and gain 2 Energy.",
                   upgraded_description="Retain. If your Hand is empty, draw 3 cards and gain 3 Energy."),
    lambda: _card("Seeker Strike", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_seeker_strike,
                   values={"damage": 9}, upgrade_values={"damage": 12},
                   description="Deal 9 damage. Choose 1 of 3 cards in your Draw Pile to add into your Hand.",
                   upgraded_description="Deal 12 damage. Choose 1 of 3 cards in your Draw Pile to add into your Hand."),
    lambda: _card("Stratagem", 1, CardType.POWER, TargetMode.SELF, fx_stratagem,
                   upgrade_cost=0,
                   description="Whenever you shuffle your Draw Pile, choose a card from it to put into your Hand.",
                   upgraded_description="Whenever you shuffle your Draw Pile, choose a card from it to put into your Hand."),
    lambda: _card("Tag Team", 2, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_tag_team,
                   values={"damage": 11}, upgrade_values={"damage": 15}, is_multiplayer=True,
                   description="Deal 11 damage. The next Attack another player plays on the enemy is played an extra time.",
                   upgraded_description="Deal 15 damage. The next Attack another player plays on the enemy is played an extra time."),
    lambda: _card("The Ball", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_the_ball,
                   values={"damage": 10, "bonus": 10}, upgrade_values={"damage": 10, "bonus": 15},
                   is_multiplayer=True,
                   description="Deal 10 damage. Increase this card's damage by 10 this combat and give it to a random ally.",
                   upgraded_description="Deal 10 damage. Increase this card's damage by 15 this combat and give it to a random ally."),
    lambda: _card("The Bomb", 2, CardType.SKILL, TargetMode.SELF, fx_the_bomb,
                   values={"damage": 40}, upgrade_values={"damage": 50},
                   description="At the end of 3 turns, deal 40 damage to ALL enemies.",
                   upgraded_description="At the end of 3 turns, deal 50 damage to ALL enemies."),
    lambda: _card("Thinking Ahead", 0, CardType.SKILL, TargetMode.SELF, fx_thinking_ahead,
                   values={"draw": 2}, exhausts=True, loses_exhaust_on_upgrade=True,
                   description="Draw 2 cards. Put 1 card from your Hand on top of your Draw Pile. Exhaust.",
                   upgraded_description="Draw 2 cards. Put 1 card from your Hand on top of your Draw Pile."),
    lambda: _card("Thrumming Hatchet", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_attack_then_return,
                   values={"damage": 11}, upgrade_values={"damage": 14},
                   description="Deal 11 damage. At the start of your next turn, return this to your Hand.",
                   upgraded_description="Deal 14 damage. At the start of your next turn, return this to your Hand."),
    lambda: _card("Volley", "X", CardType.ATTACK, TargetMode.SELF, fx_volley,
                   values={"damage": 10}, upgrade_values={"damage": 14},
                   description="Deal 10 damage to a random enemy X times.",
                   upgraded_description="Deal 14 damage to a random enemy X times."),
    lambda: _card("Alchemize", 1, CardType.SKILL, TargetMode.SELF, fx_alchemize,
                   upgrade_cost=0, exhausts=True,
                   description="Procure a random potion. Exhaust.",
                   upgraded_description="Procure a random potion. Exhaust."),
    lambda: _card("Anointed", 1, CardType.SKILL, TargetMode.SELF, fx_anointed,
                   retain_on_upgrade=True, exhausts=True,
                   description="Put every Rare card from your Draw Pile into your Hand. Exhaust.",
                   upgraded_description="Retain. Put every Rare card from your Draw Pile into your Hand. Exhaust."),
    lambda: _card("Beacon of Hope", 2, CardType.POWER, TargetMode.SELF, fx_beacon_of_hope,
                   innate_on_upgrade=True, is_multiplayer=True,
                   description="Whenever you gain Block on your turn, other players gain half that much Block.",
                   upgraded_description="Innate. Whenever you gain Block on your turn, other players gain half that much Block."),
    lambda: _card("Bolas", 0, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_attack_then_return,
                   values={"damage": 3}, upgrade_values={"damage": 4},
                   description="Deal 3 damage. At the start of your next turn, return this to your Hand.",
                   upgraded_description="Deal 4 damage. At the start of your next turn, return this to your Hand."),
    lambda: _card("Calamity", 3, CardType.POWER, TargetMode.SELF, fx_calamity,
                   upgrade_cost=2,
                   description="Whenever you play an Attack, add a random Attack into your Hand.",
                   upgraded_description="Whenever you play an Attack, add a random Attack into your Hand."),
    lambda: _card("Entropy", 1, CardType.POWER, TargetMode.SELF, fx_entropy,
                   innate_on_upgrade=True,
                   description="At the start of your turn, Transform 1 card in your Hand.",
                   upgraded_description="Innate. At the start of your turn, Transform 1 card in your Hand."),
    lambda: _card("Gold Axe", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_gold_axe,
                   retain_on_upgrade=True,
                   description="Deal damage equal to the number of cards played this combat.",
                   upgraded_description="Retain. Deal damage equal to the number of cards played this combat."),
    lambda: _card("Hand of Greed", 2, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_plain_attack,
                   values={"damage": 20}, upgrade_values={"damage": 25},
                   description="Deal 20 damage. (Gold clause not modeled.)",
                   upgraded_description="Deal 25 damage. (Gold clause not modeled.)"),
    lambda: _card("Hidden Gem", 1, CardType.SKILL, TargetMode.SELF, fx_hidden_gem,
                   values={"replay": 2}, upgrade_values={"replay": 3},
                   description="A random card in your Draw Pile without Replay gains Replay 2.",
                   upgraded_description="A random card in your Draw Pile without Replay gains Replay 3."),
    lambda: _card("Jackpot", 3, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_jackpot,
                   values={"damage": 25}, upgrade_values={"damage": 30},
                   description="Deal 25 damage. Add 3 random 0 Energy cards into your Hand.",
                   upgraded_description="Deal 30 damage. Add 3 random Upgraded 0 Energy cards into your Hand."),
    lambda: _card("Knockdown", 3, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_knockdown,
                   values={"damage": 10, "mult": 2}, upgrade_values={"damage": 14, "mult": 3},
                   is_multiplayer=True,
                   description="Deal 10 damage. The enemy takes double damage from other players this turn.",
                   upgraded_description="Deal 14 damage. The enemy takes triple damage from other players this turn."),
    lambda: _card("Mayhem", 2, CardType.POWER, TargetMode.SELF, fx_mayhem,
                   upgrade_cost=1,
                   description="At the start of your turn, play the top card of your Draw Pile.",
                   upgraded_description="At the start of your turn, play the top card of your Draw Pile."),
    lambda: _card("Mimic", 1, CardType.SKILL, TargetMode.SELF, fx_mimic,
                   exhausts=True, loses_exhaust_on_upgrade=True, is_multiplayer=True,
                   description="Gain Block equal to the Block on another player. Exhaust.",
                   upgraded_description="Gain Block equal to the Block on another player."),
    lambda: _card("Nostalgia", 1, CardType.POWER, TargetMode.SELF, fx_nostalgia,
                   upgrade_cost=0,
                   description="The first Attack or Skill you play each turn is placed on top of your Draw Pile.",
                   upgraded_description="The first Attack or Skill you play each turn is placed on top of your Draw Pile."),
    lambda: _card("Rolling Boulder", 3, CardType.POWER, TargetMode.SELF, fx_rolling_boulder,
                   values={"damage": 5}, upgrade_values={"damage": 10},
                   description="At the start of your turn, deal 5 damage to ALL enemies and increase this damage by 5.",
                   upgraded_description="At the start of your turn, deal 10 damage to ALL enemies and increase this damage by 5."),
    lambda: _card("Salvo", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_salvo,
                   values={"damage": 12}, upgrade_values={"damage": 16},
                   description="Deal 12 damage. Retain your Hand this turn.",
                   upgraded_description="Deal 16 damage. Retain your Hand this turn."),
    lambda: _card("Scrawl", 1, CardType.SKILL, TargetMode.SELF, fx_scrawl,
                   retain_on_upgrade=True, exhausts=True,
                   description="Draw cards until your Hand is full. Exhaust.",
                   upgraded_description="Retain. Draw cards until your Hand is full. Exhaust."),
    lambda: _card("The Gambit", 0, CardType.SKILL, TargetMode.SELF, fx_the_gambit,
                   values={"block": 50}, upgrade_values={"block": 75},
                   description="Gain 50 Block. If you take unblocked attack damage this combat, die.",
                   upgraded_description="Gain 75 Block. If you take unblocked attack damage this combat, die."),
    lambda: _card("Byrd Swoop", 0, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_plain_attack,
                   values={"damage": 14}, upgrade_values={"damage": 18},
                   description="Deal 14 damage.",
                   upgraded_description="Deal 18 damage."),
    lambda: _card("Enlightenment", 0, CardType.SKILL, TargetMode.SELF, fx_enlightenment,
                   exhausts=True,
                   description="Reduce the cost of ALL cards in your Hand to 1 this turn. Exhaust.",
                   upgraded_description="Reduce the cost of ALL cards in your Hand to 1 this combat. Exhaust."),
    lambda: _card("Exterminate", 1, CardType.ATTACK, TargetMode.ALL_ENEMIES, fx_exterminate,
                   values={"damage": 3}, upgrade_values={"damage": 4},
                   description="Deal 3 damage to ALL enemies 4 times.",
                   upgraded_description="Deal 4 damage to ALL enemies 4 times."),
    lambda: _card("Feeding Frenzy", 0, CardType.SKILL, TargetMode.SELF, fx_feeding_frenzy,
                   values={"strength": 5}, upgrade_values={"strength": 7},
                   description="Gain 5 Strength this turn.",
                   upgraded_description="Gain 7 Strength this turn."),
    lambda: _card("Metamorphosis", 2, CardType.SKILL, TargetMode.SELF, fx_metamorphosis,
                   values={"count": 3}, upgrade_values={"count": 5}, exhausts=True,
                   description="Add 3 random Attacks into your Draw Pile. They're free to play this combat. Exhaust.",
                   upgraded_description="Add 5 random Attacks into your Draw Pile. They're free to play this combat. Exhaust."),
    lambda: _card("Peck", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_peck_card,
                   values={"damage": 2, "hits": 3}, upgrade_values={"damage": 2, "hits": 4},
                   description="Deal 2 damage 3 times.",
                   upgraded_description="Deal 2 damage 4 times."),
    lambda: _card("Squash", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_squash,
                   values={"damage": 10, "vulnerable": 2},
                   upgrade_values={"damage": 12, "vulnerable": 3},
                   description="Deal 10 damage. Apply 2 Vulnerable.",
                   upgraded_description="Deal 12 damage. Apply 3 Vulnerable."),
    lambda: _card("Toric Toughness", 2, CardType.SKILL, TargetMode.SELF, fx_toric_toughness,
                   values={"block": 5}, upgrade_values={"block": 7},
                   description="Gain 5 Block. Gain 5 Block at the start of the next 2 turns.",
                   upgraded_description="Gain 7 Block. Gain 7 Block at the start of the next 2 turns."),
    lambda: _card("Clash", 0, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_plain_attack,
                   values={"damage": 14}, upgrade_values={"damage": 18},
                   playable_if=_clash_playable,
                   description="Can only be played if every card in your Hand is an Attack. Deal 14 damage.",
                   upgraded_description="Can only be played if every card in your Hand is an Attack. Deal 18 damage."),
    lambda: _card("Dual Wield", 1, CardType.SKILL, TargetMode.SELF, fx_dual_wield,
                   values={"copies": 1}, upgrade_values={"copies": 2},
                   description="Choose an Attack or Power card. Add a copy of that card into your Hand.",
                   upgraded_description="Choose an Attack or Power card. Add 2 copies of that card into your Hand."),
    lambda: _card("Distraction", 1, CardType.SKILL, TargetMode.SELF, fx_distraction,
                   upgrade_cost=0, exhausts=True,
                   description="Add a random Skill into your Hand. It's free to play this turn. Exhaust.",
                   upgraded_description="Add a random Skill into your Hand. It's free to play this turn. Exhaust."),
    lambda: _card("Outmaneuver", 1, CardType.SKILL, TargetMode.SELF, fx_outmaneuver,
                   values={"energy": 2}, upgrade_values={"energy": 3},
                   description="Next turn, gain 2 Energy.",
                   upgraded_description="Next turn, gain 3 Energy."),
    lambda: _card("Hello World", 1, CardType.POWER, TargetMode.SELF, fx_hello_world,
                   innate_on_upgrade=True,
                   description="At the start of your turn, add a random Common card into your Hand.",
                   upgraded_description="Innate. At the start of your turn, add a random Common card into your Hand."),
    lambda: _card("Rebound", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_rebound,
                   values={"damage": 9}, upgrade_values={"damage": 12},
                   description="Deal 9 damage. Put the next card you play this turn on top of your Draw Pile.",
                   upgraded_description="Deal 12 damage. Put the next card you play this turn on top of your Draw Pile."),
    lambda: _card("Rip and Tear", 1, CardType.ATTACK, TargetMode.SELF, fx_rip_and_tear,
                   values={"damage": 7}, upgrade_values={"damage": 9},
                   description="Deal 7 damage to a random enemy twice.",
                   upgraded_description="Deal 9 damage to a random enemy twice."),
    lambda: _card("Stack", 1, CardType.SKILL, TargetMode.SELF, fx_stack,
                   values={"bonus": 0}, upgrade_values={"bonus": 3},
                   description="Gain Block equal to the number of cards in your Discard Pile.",
                   upgraded_description="Gain Block equal to the number of cards in your Discard Pile +3."),
    lambda: _card("Mad Science (Sapping)", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_mad_sapping,
                   values={"damage": 12}, innate_on_upgrade=True,
                   description="Deal 12 damage. Apply 2 Weak. Apply 2 Vulnerable.",
                   upgraded_description="Innate. Deal 12 damage. Apply 2 Weak. Apply 2 Vulnerable."),
    lambda: _card("Mad Science (Violence)", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_mad_violence,
                   values={"damage": 12}, innate_on_upgrade=True,
                   description="Deal 12 damage 3 times.",
                   upgraded_description="Innate. Deal 12 damage 3 times."),
    lambda: _card("Mad Science (Choking)", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_mad_choking,
                   values={"damage": 12}, innate_on_upgrade=True,
                   description="Deal 12 damage. Whenever you play a card this turn, the enemy loses 6 HP.",
                   upgraded_description="Innate. Deal 12 damage. Whenever you play a card this turn, the enemy loses 6 HP."),
    lambda: _card("Mad Science (Energized)", 1, CardType.SKILL, TargetMode.SELF, fx_mad_energized,
                   values={"block": 8}, innate_on_upgrade=True,
                   description="Gain 8 Block. Gain 2 Energy.",
                   upgraded_description="Innate. Gain 8 Block. Gain 2 Energy."),
    lambda: _card("Mad Science (Wisdom)", 1, CardType.SKILL, TargetMode.SELF, fx_mad_wisdom,
                   values={"block": 8}, innate_on_upgrade=True,
                   description="Gain 8 Block. Draw 3 cards.",
                   upgraded_description="Innate. Gain 8 Block. Draw 3 cards."),
    lambda: _card("Mad Science (Chaos)", 1, CardType.SKILL, TargetMode.SELF, fx_mad_chaos,
                   values={"block": 8}, innate_on_upgrade=True,
                   description="Gain 8 Block. Add a random card into your Hand. It's free to play this turn.",
                   upgraded_description="Innate. Gain 8 Block. Add a random card into your Hand. It's free to play this turn."),
    lambda: _card("Mad Science (Expertise)", 1, CardType.POWER, TargetMode.SELF, fx_mad_expertise,
                   innate_on_upgrade=True,
                   description="Gain 2 Strength. Gain 2 Dexterity.",
                   upgraded_description="Innate. Gain 2 Strength. Gain 2 Dexterity."),
    lambda: _card("Mad Science (Improvement)", 1, CardType.POWER, TargetMode.SELF, fx_mad_improvement,
                   innate_on_upgrade=True,
                   description="Upgrade a random card for this combat.",
                   upgraded_description="Innate. Upgrade a random card for this combat."),
    lambda: _card("Mad Science (Curious)", 1, CardType.POWER, TargetMode.SELF, fx_mad_curious,
                   innate_on_upgrade=True,
                   description="Powers cost 1 Energy less.",
                   upgraded_description="Innate. Powers cost 1 Energy less."),
])


ANCIENT_COLORLESS: List[Callable[[], Card]] = [
    lambda: _card("Apotheosis", 2, CardType.SKILL, TargetMode.SELF, fx_apotheosis,
                   upgrade_cost=1, innate=True, exhausts=True,
                   description="Innate. Upgrade ALL your cards. Exhaust.",
                   upgraded_description="Innate. Upgrade ALL your cards. Exhaust."),
    lambda: _card("Apparition", 1, CardType.SKILL, TargetMode.SELF, fx_apparition,
                   values={"intangible": 1}, ethereal=True,
                   loses_ethereal_on_upgrade=True, exhausts=True,
                   description="Ethereal. Gain 1 Intangible. Exhaust.",
                   upgraded_description="Gain 1 Intangible. Exhaust."),
    lambda: _card("Brightest Flame", 0, CardType.SKILL, TargetMode.SELF, fx_brightest_flame,
                   values={"energy": 2, "draw": 2}, upgrade_values={"energy": 3, "draw": 3},
                   description="Gain 2 Energy. Draw 2 cards. Lose 1 Max HP.",
                   upgraded_description="Gain 3 Energy. Draw 3 cards. Lose 1 Max HP."),
    lambda: _card("Maul", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_maul,
                   values={"damage": 5, "bonus": 2}, upgrade_values={"damage": 6, "bonus": 3},
                   description="Deal 5 damage twice. Increase the damage of ALL Maul cards by 2 this combat.",
                   upgraded_description="Deal 6 damage twice. Increase the damage of ALL Maul cards by 3 this combat."),
    lambda: _card("Neow's Fury", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_neows_fury,
                   values={"damage": 10, "count": 2}, upgrade_values={"damage": 14, "count": 3},
                   exhausts=True,
                   description="Deal 10 damage. Put up to 2 cards from your Discard Pile into your Hand. Exhaust.",
                   upgraded_description="Deal 14 damage. Put up to 3 cards from your Discard Pile into your Hand. Exhaust."),
    lambda: _card("Abundance", 1, CardType.SKILL, TargetMode.SELF, fx_abundance,
                   exhausts=True,
                   description="Choose 1 of 3 Powers to add into your Hand. It's free to play this turn. Exhaust.",
                   upgraded_description="Choose 1 of 3 Powers to add into your Hand. It's free to play this turn. Exhaust."),
    lambda: _card("Relax", 3, CardType.SKILL, TargetMode.SELF, fx_relax,
                   values={"block": 16, "draw": 2, "energy": 2},
                   upgrade_values={"block": 18, "draw": 3, "energy": 3}, exhausts=True,
                   description="Gain 16 Block. Next turn, draw 2 cards and gain 2 Energy. Exhaust.",
                   upgraded_description="Gain 18 Block. Next turn, draw 3 cards and gain 3 Energy. Exhaust."),
    lambda: _card("Whistle", 2, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_whistle,
                   values={"damage": 33}, upgrade_values={"damage": 44}, exhausts=True,
                   description="Deal 33 damage. Stun the enemy. Exhaust.",
                   upgraded_description="Deal 44 damage. Stun the enemy. Exhaust."),
    lambda: _card("Wish", 0, CardType.SKILL, TargetMode.SELF, fx_wish,
                   retain_on_upgrade=True, exhausts=True,
                   description="Put a card from your Draw Pile into your Hand. Exhaust.",
                   upgraded_description="Retain. Put a card from your Draw Pile into your Hand. Exhaust."),
]


CURSE_POOL: List[Callable[[], Card]] = [
    lambda: _curse("Ascender's Bane", "Unplayable. Ethereal. Eternal.",
                    ethereal=True, eternal=True),
    lambda: _curse("Bad Luck",
                    "Unplayable. At the end of your turn, if this is in your Hand, lose 13 HP. Eternal.",
                    eternal=True),
    lambda: _curse("Clumsy", "Unplayable. Ethereal.", ethereal=True),
    lambda: _curse("Curse of the Bell", "Unplayable. Eternal.", eternal=True),
    lambda: _curse("Debt", "Unplayable. (Gold clause not modeled.)"),
    lambda: _curse("Decay",
                    "Unplayable. At the end of your turn, if this is in your Hand, take 2 damage."),
    lambda: _curse("Doubt",
                    "Unplayable. At the end of your turn, if this is in your Hand, gain 1 Weak."),
    lambda: _curse("Enthralled",
                    "If this is in your Hand, it must be played before other cards. Eternal.",
                    cost=2, effect=fx_enthralled, eternal=True),
    lambda: _curse("Folly", "Unplayable. Ethereal. Innate. Eternal.",
                    ethereal=True, innate=True, eternal=True),
    lambda: _curse("Greed", "Unplayable. Eternal.", eternal=True),
    lambda: _curse("Guilty",
                    "Unplayable. Removed from your Deck after 5 combats. (Removal not modeled.)"),
    lambda: _curse("Injury", "Unplayable."),
    lambda: _curse("Normality", "Unplayable. You cannot play more than 3 cards this turn."),
    lambda: _curse("Poor Sleep", "Unplayable. Retain.", retain=True),
    lambda: _curse("Regret",
                    "Unplayable. At the end of your turn, if this is in your Hand, lose 1 HP for each card in your Hand."),
    lambda: _curse("Shame",
                    "Unplayable. At the end of your turn, if this is in your Hand, gain 1 Frail."),
    lambda: _curse("Spore Mind", "Exhaust.", cost=1, effect=fx_clear_away, exhausts=True),
    lambda: _curse("Writhe", "Unplayable. Innate.", innate=True),
]


_COLORLESS_CARDS.update({
    "Automation", "Believe in You", "Coordinate", "Discovery", "Equilibrium",
    "Fasten", "Gang Up", "Huddle Up", "Intercept", "Jack of All Trades",
    "Lift", "Panache", "Panic Button", "Prep Time", "Production", "Prolong",
    "Purity", "Restlessness", "Seeker Strike", "Stratagem", "Tag Team",
    "The Ball", "The Bomb", "Thinking Ahead", "Thrumming Hatchet", "Volley",
    "Alchemize", "Anointed", "Beacon of Hope", "Bolas", "Calamity", "Entropy",
    "Gold Axe", "Hand of Greed", "Hidden Gem", "Jackpot", "Knockdown",
    "Mayhem", "Mimic", "Nostalgia", "Rolling Boulder", "Salvo", "Scrawl",
    "The Gambit", "Byrd Swoop", "Enlightenment", "Exterminate",
    "Feeding Frenzy", "Metamorphosis", "Peck", "Squash", "Toric Toughness",
    "Clash", "Dual Wield", "Distraction", "Outmaneuver", "Hello World",
    "Rebound", "Rip and Tear", "Stack",
    "Mad Science (Sapping)", "Mad Science (Violence)", "Mad Science (Choking)",
    "Mad Science (Energized)", "Mad Science (Wisdom)", "Mad Science (Chaos)",
    "Mad Science (Expertise)", "Mad Science (Improvement)",
    "Mad Science (Curious)",
})


_ANCIENT_CARDS.update({
    "Apotheosis", "Apparition", "Brightest Flame", "Maul", "Neow's Fury",
    "Abundance", "Relax", "Whistle", "Wish",
})


def make_starter_deck() -> List[Card]:
    """Real Ironclad starting deck (per STS2 wiki): 5 Strike, 4 Defend, 1 Bash."""
    deck = []
    for _ in range(5):
        deck.append(Card(
            "Strike", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_plain_attack,
            values={"damage": 6}, upgrade_values={"damage": 9},
            description="Deal 6 damage.", upgraded_description="Deal 9 damage.",
        ))
    for _ in range(4):
        deck.append(Card(
            "Defend", 1, CardType.SKILL, TargetMode.SELF, fx_defend,
            values={"block": 5}, upgrade_values={"block": 8},
            description="Gain 5 Block.", upgraded_description="Gain 8 Block.",
        ))
    deck.append(Card(
        "Bash", 2, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_attack_vulnerable,
        values={"damage": 8, "vulnerable": 2}, upgrade_values={"damage": 10, "vulnerable": 3},
        description="Deal 8 damage. Apply 2 Vulnerable.",
        upgraded_description="Deal 10 damage. Apply 3 Vulnerable.",
    ))
    return deck


def make_coop_support_deck() -> List[Card]:
    """A second starter deck showing real STS2 multiplayer cards in action."""
    deck = []
    for _ in range(3):
        deck.append(Card(
            "Strike", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_plain_attack,
            values={"damage": 6}, upgrade_values={"damage": 9},
            description="Deal 6 damage.", upgraded_description="Deal 9 damage.",
        ))
    for _ in range(3):
        deck.append(Card(
            "Defend", 1, CardType.SKILL, TargetMode.SELF, fx_defend,
            values={"block": 5}, upgrade_values={"block": 8},
            description="Gain 5 Block.", upgraded_description="Gain 8 Block.",
        ))
    deck.append(Card(
        "True Grit", 1, CardType.SKILL, TargetMode.SELF, fx_true_grit,
        values={"block": 7}, upgrade_values={"block": 9},
        description="Gain 7 Block. Exhaust 1 card at random.",
        upgraded_description="Gain 9 Block. Exhaust 1 card.",
    ))
    deck.append(Card(
        "Blaze", 2, CardType.SKILL, TargetMode.ALLY, fx_blaze,
        values={"strength": 5}, upgrade_values={"strength": 7},
        is_multiplayer=True,
        description="Give another player 5 Strength.",
        upgraded_description="Give another player 7 Strength.",
    ))
    deck.append(Card(
        "Demonic Shield", 0, CardType.SKILL, TargetMode.ALLY, fx_demonic_shield,
        values={"hploss": 1}, exhausts=True, loses_exhaust_on_upgrade=True,
        is_multiplayer=True,
        description="Lose 1 HP. Give another player Block equal to your Block. Exhaust.",
        upgraded_description="Lose 1 HP. Give another player Block equal to your Block.",
    ))
    return deck


def _card(name, cost, ctype, target, effect, **kw) -> Card:
    return Card(name, cost, ctype, target, effect, **kw)


CARD_POOL_IRONCLAD: List[Callable[[], Card]] = [
    lambda: _card("Anger", 0, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_anger,
                   values={"damage": 6}, upgrade_values={"damage": 8},
                   description="Deal 6 damage. Add a copy of this card into your Discard Pile.",
                   upgraded_description="Deal 8 damage. Add a copy of this card into your Discard Pile."),
    lambda: _card("Armaments", 1, CardType.SKILL, TargetMode.SELF, fx_armaments,
                   values={"block": 5},
                   description="Gain 5 Block. Upgrade a card in your Hand.",
                   upgraded_description="Gain 5 Block. Upgrade ALL cards in your Hand."),
    lambda: _card("Blood Wall", 2, CardType.SKILL, TargetMode.SELF, fx_blood_wall,
                   values={"hploss": 2, "block": 16}, upgrade_values={"block": 20},
                   description="Lose 2 HP. Gain 16 Block.",
                   upgraded_description="Lose 2 HP. Gain 20 Block."),
    lambda: _card("Body Slam", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_body_slam,
                   upgrade_cost=0,
                   description="Deal damage equal to your Block.",
                   upgraded_description="Deal damage equal to your Block."),
    lambda: _card("Breakthrough", 1, CardType.ATTACK, TargetMode.ALL_ENEMIES, fx_breakthrough,
                   values={"hploss": 1, "damage": 9}, upgrade_values={"damage": 13},
                   description="Lose 1 HP. Deal 9 damage to ALL enemies.",
                   upgraded_description="Lose 1 HP. Deal 13 damage to ALL enemies."),
    lambda: _card("Cinder", 2, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_cinder,
                   values={"damage": 18}, upgrade_values={"damage": 24},
                   description="Deal 18 damage. Exhaust a random card in your Hand.",
                   upgraded_description="Deal 24 damage. Exhaust a random card in your Hand."),
    lambda: _card("Headbutt", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_headbutt,
                   values={"damage": 9}, upgrade_values={"damage": 12},
                   description="Deal 9 damage. Put a card from your Discard Pile on top of your Draw Pile.",
                   upgraded_description="Deal 12 damage. Put a card from your Discard Pile on top of your Draw Pile."),
    lambda: _card("Iron Wave", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_iron_wave,
                   values={"block": 5, "damage": 5}, upgrade_values={"block": 7, "damage": 7},
                   description="Gain 5 Block. Deal 5 damage.",
                   upgraded_description="Gain 7 Block. Deal 7 damage."),
    lambda: _card("Molten Fist", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_molten_fist,
                   values={"damage": 10}, upgrade_values={"damage": 14}, exhausts=True,
                   description="Deal 10 damage. Double the enemy's Vulnerable. Exhaust.",
                   upgraded_description="Deal 14 damage. Double the enemy's Vulnerable. Exhaust."),
    lambda: _card("Perfected Strike", 2, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_perfected_strike,
                   values={"damage": 6, "extradamage": 2}, upgrade_values={"extradamage": 3},
                   description='Deal 6 damage. Deals 2 additional damage for ALL your cards containing "Strike".',
                   upgraded_description='Deal 6 damage. Deals 3 additional damage for ALL your cards containing "Strike".'),
    lambda: _card("Pommel Strike", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_pommel_strike,
                   values={"damage": 9, "cards": 1}, upgrade_values={"damage": 10, "cards": 2},
                   description="Deal 9 damage. Draw 1 card.",
                   upgraded_description="Deal 10 damage. Draw 2 cards."),
    lambda: _card("Setup Strike", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_setup_strike,
                   values={"damage": 7, "strength": 3}, upgrade_values={"damage": 9, "strength": 4},
                   description="Deal 7 damage. Gain 3 Strength this turn.",
                   upgraded_description="Deal 9 damage. Gain 4 Strength this turn."),
    lambda: _card("Shrug It Off", 1, CardType.SKILL, TargetMode.SELF, fx_shrug_it_off,
                   values={"block": 8, "cards": 1}, upgrade_values={"block": 11},
                   description="Gain 8 Block. Draw 1 card.",
                   upgraded_description="Gain 11 Block. Draw 1 card."),
    lambda: _card("Sword Boomerang", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_sword_boomerang,
                   values={"damage": 3, "repeat": 3}, upgrade_values={"repeat": 4},
                   description="Deal 3 damage to a random enemy 3 times.",
                   upgraded_description="Deal 3 damage to a random enemy 4 times."),
    lambda: _card("Taunt", 1, CardType.SKILL, TargetMode.SINGLE_ENEMY, fx_taunt,
                   values={"block": 6, "vulnerable": 1}, upgrade_values={"block": 7, "vulnerable": 2},
                   description="Gain 6 Block. Apply 1 Vulnerable.",
                   upgraded_description="Gain 7 Block. Apply 2 Vulnerable."),
    lambda: _card("Thunderclap", 1, CardType.ATTACK, TargetMode.ALL_ENEMIES, fx_thunderclap,
                   values={"damage": 4, "vulnerable": 1}, upgrade_values={"damage": 7},
                   description="Deal 4 damage and apply 1 Vulnerable to ALL enemies.",
                   upgraded_description="Deal 7 damage and apply 1 Vulnerable to ALL enemies."),
    lambda: _card("Tremble", 1, CardType.SKILL, TargetMode.SINGLE_ENEMY, fx_tremble,
                   values={"vulnerable": 3}, upgrade_values={"vulnerable": 4}, exhausts=True,
                   description="Apply 3 Vulnerable. Exhaust.",
                   upgraded_description="Apply 4 Vulnerable. Exhaust."),
    lambda: _card("True Grit", 1, CardType.SKILL, TargetMode.SELF, fx_true_grit,
                   values={"block": 7}, upgrade_values={"block": 9},
                   description="Gain 7 Block. Exhaust 1 card at random.",
                   upgraded_description="Gain 9 Block. Exhaust 1 card."),
    lambda: _card("Twin Strike", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_twin_strike,
                   values={"damage": 5}, upgrade_values={"damage": 7},
                   description="Deal 5 damage twice.",
                   upgraded_description="Deal 7 damage twice."),
    lambda: _card("Battle Trance", 0, CardType.SKILL, TargetMode.SELF, fx_battle_trance,
                   values={"cards": 3}, upgrade_values={"cards": 4},
                   description="Draw 3 cards. You cannot draw additional cards this turn.",
                   upgraded_description="Draw 4 cards. You cannot draw additional cards this turn."),
    lambda: _card("Havoc", 1, CardType.SKILL, TargetMode.SINGLE_ENEMY, fx_havoc,
                   upgrade_cost=0,
                   description="Play the top card of your Draw Pile and Exhaust it.",
                   upgraded_description="Play the top card of your Draw Pile and Exhaust it."),
    lambda: _card("Whirlwind", "X", CardType.ATTACK, TargetMode.ALL_ENEMIES, fx_whirlwind,
                   values={"damage": 5}, upgrade_values={"damage": 8},
                   description="Deal 5 damage to ALL enemies X times.",
                   upgraded_description="Deal 8 damage to ALL enemies X times."),
    lambda: _card("Blaze", 2, CardType.SKILL, TargetMode.ALLY, fx_blaze,
                   values={"strength": 5}, upgrade_values={"strength": 7}, is_multiplayer=True,
                   description="Give another player 5 Strength.",
                   upgraded_description="Give another player 7 Strength."),
    lambda: _card("Demonic Shield", 0, CardType.SKILL, TargetMode.ALLY, fx_demonic_shield,
                   values={"hploss": 1}, exhausts=True, loses_exhaust_on_upgrade=True, is_multiplayer=True,
                   description="Lose 1 HP. Give another player Block equal to your Block. Exhaust.",
                   upgraded_description="Lose 1 HP. Give another player Block equal to your Block."),
    lambda: _card("Tank", 1, CardType.POWER, TargetMode.SELF, fx_tank,
                   is_multiplayer=True, upgrade_cost=0,
                   description="Take 50% additional damage from enemies. Allies take 50% less damage from enemies.",
                   upgraded_description="Take 50% additional damage from enemies. Allies take 50% less damage from enemies."),
    lambda: _card("Dark Embrace", 2, CardType.POWER, TargetMode.SELF, fx_dark_embrace,
                   upgrade_cost=1,
                   description="Whenever a card is Exhausted, draw 1 card.",
                   upgraded_description="Whenever a card is Exhausted, draw 1 card."),
    lambda: _card("Feel No Pain", 1, CardType.POWER, TargetMode.SELF, fx_feel_no_pain,
                   values={"block": 3}, upgrade_values={"block": 4},
                   description="Whenever a card is Exhausted, gain 3 Block.",
                   upgraded_description="Whenever a card is Exhausted, gain 4 Block."),
    lambda: _card("Rage", 0, CardType.SKILL, TargetMode.SELF, fx_rage,
                   values={"block": 3}, upgrade_values={"block": 5},
                   description="Whenever you play an Attack this turn, gain 3 Block.",
                   upgraded_description="Whenever you play an Attack this turn, gain 5 Block."),

    lambda: _card("Bloodletting", 1, CardType.SKILL, TargetMode.SELF, fx_bloodletting,
                   values={"hploss": 3, "energy": 2}, upgrade_values={"energy": 3},
                   description="Lose 3 HP. Gain 2 Energy.",
                   upgraded_description="Lose 3 HP. Gain 3 Energy."),
    lambda: _card("Bludgeon", 2, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_plain_attack,
                   values={"damage": 32}, upgrade_values={"damage": 42},
                   description="Deal 32 damage.",
                   upgraded_description="Deal 42 damage."),
    lambda: _card("Bully", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_bully,
                   values={"damage": 4, "extradamage": 2}, upgrade_values={"extradamage": 3},
                   description="Deal 4 damage. Deals 2 additional damage for each Vulnerable on the enemy.",
                   upgraded_description="Deal 4 damage. Deals 3 additional damage for each Vulnerable on the enemy."),
    lambda: _card("Dismantle", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_dismantle,
                   values={"damage": 8}, upgrade_values={"damage": 10},
                   description="Deal 8 damage. If the enemy is Vulnerable, hits twice.",
                   upgraded_description="Deal 10 damage. If the enemy is Vulnerable, hits twice."),
    lambda: _card("Evil Eye", 1, CardType.SKILL, TargetMode.SELF, fx_evil_eye,
                   values={"block": 8}, upgrade_values={"block": 11},
                   description="Gain 8 Block. Gain another 8 Block if you have Exhausted a card this turn.",
                   upgraded_description="Gain 11 Block. Gain another 11 Block if you have Exhausted a card this turn."),
    lambda: _card("Expect a Fight", 2, CardType.SKILL, TargetMode.SELF, fx_expect_a_fight,
                   values={"block": 15, "extrablock": 5}, upgrade_values={"block": 16, "extrablock": 8},
                   description="Gain 15 Block. Gains 5 additional Block for each Strength you have.",
                   upgraded_description="Gain 16 Block. Gains 8 additional Block for each Strength you have."),
    lambda: _card("Fight Me!", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_fight_me,
                   values={"damage": 5, "strength": 3}, upgrade_values={"damage": 6, "strength": 4},
                   description="Deal 5 damage twice. Gain 3 Strength. The enemy gains 1 Strength.",
                   upgraded_description="Deal 6 damage twice. Gain 4 Strength. The enemy gains 1 Strength."),
    lambda: _card("Hemokinesis", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_hemokinesis,
                   values={"hploss": 2, "damage": 15}, upgrade_values={"damage": 20},
                   description="Lose 2 HP. Deal 15 damage.",
                   upgraded_description="Lose 2 HP. Deal 20 damage."),
    lambda: _card("Inflame", 1, CardType.POWER, TargetMode.SELF, fx_inflame,
                   values={"strength": 2}, upgrade_values={"strength": 3},
                   description="Gain 2 Strength.",
                   upgraded_description="Gain 3 Strength."),
    lambda: _card("Outrage", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_outrage,
                   values={"damage": 9}, upgrade_values={"damage": 13},
                   description="Deal 9 damage. Add a copy of this card into EVERYONE'S Discard Pile.",
                   upgraded_description="Deal 13 damage. Add a copy of this card into EVERYONE'S Discard Pile."),
    lambda: _card("Spite", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_spite,
                   values={"damage": 5, "hits": 2}, upgrade_values={"hits": 3},
                   description="Deal 5 damage. If you lost HP this turn, hits 2 times.",
                   upgraded_description="Deal 5 damage. If you lost HP this turn, hits 3 times."),
    lambda: _card("Stone Armor", 1, CardType.SKILL, TargetMode.SELF, fx_stone_armor,
                   values={"plating": 4}, upgrade_values={"plating": 6},
                   description="Gain 4 Plating.",
                   upgraded_description="Gain 6 Plating."),
    lambda: _card("Uppercut", 2, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_uppercut,
                   values={"damage": 13, "weak": 1, "vulnerable": 1}, upgrade_values={"weak": 2, "vulnerable": 2},
                   description="Deal 13 damage. Apply 1 Weak. Apply 1 Vulnerable.",
                   upgraded_description="Deal 13 damage. Apply 2 Weak. Apply 2 Vulnerable."),
    lambda: _card("Ashen Strike", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_ashen_strike,
                   values={"damage": 6, "extradamage": 3}, upgrade_values={"extradamage": 4},
                   description='Deal 6 damage. Deals 3 additional damage for each card in your Exhaust Pile.',
                   upgraded_description='Deal 6 damage. Deals 4 additional damage for each card in your Exhaust Pile.'),
    lambda: _card("Infernal Blade", 1, CardType.SKILL, TargetMode.SELF, fx_infernal_blade,
                   exhausts=True,
                   description="Add a random Attack into your Hand. It's free to play this turn. Exhaust.",
                   upgraded_description="Add a random Attack into your Hand. It's free to play this turn. Exhaust."),
    lambda: _card("Second Wind", 1, CardType.SKILL, TargetMode.SELF, fx_second_wind,
                   values={"block": 5}, upgrade_values={"block": 7},
                   description="Exhaust all non-Attack cards in your Hand. Gain 5 Block for each card Exhausted.",
                   upgraded_description="Exhaust all non-Attack cards in your Hand. Gain 7 Block for each card Exhausted."),
    lambda: _card("Forgotten Ritual", 1, CardType.SKILL, TargetMode.SELF, fx_plain_energy,
                   values={"energy": 3}, upgrade_values={"energy": 4}, exhausts=True,
                   description="Gain 3 Energy. Exhaust.",
                   upgraded_description="Gain 4 Energy. Exhaust."),
    lambda: _card("Rupture", 1, CardType.POWER, TargetMode.SELF, fx_rupture,
                   values={"strength": 1}, upgrade_values={"strength": 2},
                   description="Whenever you lose HP on your turn, gain 1 Strength.",
                   upgraded_description="Whenever you lose HP on your turn, gain 2 Strength."),
    lambda: _card("Inferno", 2, CardType.POWER, TargetMode.SELF, fx_inferno,
                   values={"damage": 6}, upgrade_values={"damage": 9},
                   description="At the start of your turn, lose 1 HP. Whenever you lose HP on your turn, deal 6 damage to ALL enemies.",
                   upgraded_description="At the start of your turn, lose 1 HP. Whenever you lose HP on your turn, deal 9 damage to ALL enemies."),
    lambda: _card("Burning Pact", 1, CardType.SKILL, TargetMode.SELF, fx_burning_pact,
                   values={"cards": 2}, upgrade_values={"cards": 3},
                   description="Exhaust 1 card. Draw 2 cards.",
                   upgraded_description="Exhaust 1 card. Draw 3 cards."),
    lambda: _card("Drum of Battle", 1, CardType.SKILL, TargetMode.SELF, fx_drum_of_battle,
                   values={"cards": 2, "energy": 2}, upgrade_values={"energy": 3},
                   description="Draw 2 cards. When this card is Exhausted, gain 2 Energy.",
                   upgraded_description="Draw 2 cards. When this card is Exhausted, gain 3 Energy."),

    lambda: _card("Barricade", 3, CardType.POWER, TargetMode.SELF, fx_barricade,
                   upgrade_cost=2,
                   description="Block is not removed at the start of your turn.",
                   upgraded_description="Block is not removed at the start of your turn."),
    lambda: _card("Cascade", "X", CardType.SKILL, TargetMode.SELF, fx_cascade,
                   description="Play the top X cards of your Draw Pile.",
                   upgraded_description="Play the top X+1 cards of your Draw Pile."),
    lambda: _card("Conflagration", 1, CardType.ATTACK, TargetMode.ALL_ENEMIES, fx_conflagration,
                   values={"damage": 2, "repeat": 4}, upgrade_values={"repeat": 5},
                   description="Deal 2 damage to ALL enemies 4 times.",
                   upgraded_description="Deal 2 damage to ALL enemies 5 times."),
    lambda: _card("Crimson Mantle", 1, CardType.POWER, TargetMode.SELF, fx_crimson_mantle,
                   values={"block": 7}, upgrade_values={"block": 10},
                   description="At the start of your turn, lose 1 HP and gain 7 Block.",
                   upgraded_description="At the start of your turn, lose 1 HP and gain 10 Block."),
    lambda: _card("Demon Form", 3, CardType.POWER, TargetMode.SELF, fx_demon_form,
                   values={"strength": 3}, upgrade_values={"strength": 4},
                   description="At the start of your turn, gain 3 Strength.",
                   upgraded_description="At the start of your turn, gain 4 Strength."),
    lambda: _card("Impervious", 2, CardType.SKILL, TargetMode.SELF, fx_plain_block,
                   values={"block": 30}, upgrade_values={"block": 40}, exhausts=True,
                   description="Gain 30 Block. Exhaust.",
                   upgraded_description="Gain 40 Block. Exhaust."),
    lambda: _card("Not Yet", 2, CardType.SKILL, TargetMode.SELF, fx_not_yet,
                   values={"heal": 10}, upgrade_values={"heal": 13}, exhausts=True,
                   description="Heal 10 HP. Exhaust.",
                   upgraded_description="Heal 13 HP. Exhaust."),
    lambda: _card("Offering", 0, CardType.SKILL, TargetMode.SELF, fx_offering,
                   values={"hploss": 6, "energy": 2, "cards": 3}, upgrade_values={"cards": 5}, exhausts=True,
                   description="Lose 6 HP. Gain 2 Energy. Draw 3 cards. Exhaust.",
                   upgraded_description="Lose 6 HP. Gain 2 Energy. Draw 5 cards. Exhaust."),
    lambda: _card("Pact's End", 0, CardType.ATTACK, TargetMode.ALL_ENEMIES, fx_pacts_end,
                   values={"damage": 18}, upgrade_values={"damage": 24},
                   description="If you have 3 or more cards in your Exhaust Pile, deal 18 damage to ALL enemies.",
                   upgraded_description="If you have 3 or more cards in your Exhaust Pile, deal 24 damage to ALL enemies."),
    lambda: _card("Pyre", 2, CardType.POWER, TargetMode.SELF, fx_pyre,
                   values={"energy": 1}, upgrade_values={"energy": 2},
                   description="Gain 1 Energy at the start of each turn.",
                   upgraded_description="Gain 2 Energy at the start of each turn."),
    lambda: _card("Tear Asunder", 2, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_tear_asunder,
                   values={"damage": 5}, upgrade_values={"damage": 7},
                   description="Deal 5 damage. Hits an additional time for each time you lost HP this combat.",
                   upgraded_description="Deal 7 damage. Hits an additional time for each time you lost HP this combat."),
    lambda: _card("Juggernaut", 2, CardType.POWER, TargetMode.SELF, fx_juggernaut,
                   values={"damage": 5}, upgrade_values={"damage": 7},
                   description="Whenever you gain Block, deal 5 damage to a random enemy.",
                   upgraded_description="Whenever you gain Block, deal 7 damage to a random enemy."),
    lambda: _card("Fiend Fire", 2, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_fiend_fire,
                   values={"damage": 7}, upgrade_values={"damage": 10}, exhausts=True,
                   description="Exhaust your Hand. Deal 7 damage for each card Exhausted. Exhaust.",
                   upgraded_description="Exhaust your Hand. Deal 10 damage for each card Exhausted. Exhaust."),
    lambda: _card("Unmovable", 2, CardType.POWER, TargetMode.SELF, fx_unmovable,
                   description="The first time you gain Block from a card each turn, double the amount gained.",
                   upgraded_description="The first time you gain Block from a card each turn, double the amount gained."),
    lambda: _card("Thrash", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_thrash,
                   values={"damage": 4}, upgrade_values={"damage": 6},
                   description="Deal 4 damage twice. Exhaust a random Attack in your Hand and add its damage to this card.",
                   upgraded_description="Deal 6 damage twice. Exhaust a random Attack in your Hand and add its damage to this card."),

    lambda: _card("Feed", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_feed,
                   values={"damage": 10, "maxhp": 3}, upgrade_values={"damage": 12, "maxhp": 4}, exhausts=True,
                   description="Deal 10 damage. If Fatal, raise your Max HP by 3. Exhaust.",
                   upgraded_description="Deal 12 damage. If Fatal, raise your Max HP by 4. Exhaust."),
    lambda: _card("Pillage", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_pillage,
                   values={"damage": 6}, upgrade_values={"damage": 9},
                   description="Deal 6 damage. Draw cards until you draw a non-Attack card.",
                   upgraded_description="Deal 9 damage. Draw cards until you draw a non-Attack card."),
    lambda: _card("Rampage", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_rampage,
                   values={"damage": 10, "increase": 5}, upgrade_values={"increase": 10},
                   description="Deal 10 damage. Increase this card's damage by 5 this combat.",
                   upgraded_description="Deal 10 damage. Increase this card's damage by 10 this combat."),

    lambda: _card("Aggression", 1, CardType.POWER, TargetMode.SELF, fx_aggression,
                   innate_on_upgrade=True,
                   description="At the start of your turn, put a random Attack from your Discard Pile into your Hand and Upgrade it.",
                   upgraded_description="Innate. At the start of your turn, put a random Attack from your Discard Pile into your Hand and Upgrade it."),
    lambda: _card("Brand", 0, CardType.SKILL, TargetMode.SELF, fx_brand,
                   values={"strength": 1}, upgrade_values={"strength": 2},
                   description="Lose 1 HP. Exhaust 1 card. Gain 1 Strength.",
                   upgraded_description="Lose 1 HP. Exhaust 1 card. Gain 2 Strength."),
    lambda: _card("Colossus", 1, CardType.SKILL, TargetMode.SELF, fx_colossus,
                   values={"block": 4}, upgrade_values={"block": 7},
                   description="Gain 4 Block. You receive 50% less damage from Vulnerable enemies this turn.",
                   upgraded_description="Gain 7 Block. You receive 50% less damage from Vulnerable enemies this turn."),
    lambda: _card("Cruelty", 1, CardType.POWER, TargetMode.SELF, fx_cruelty,
                   values={"bonus_pct": 25}, upgrade_values={"bonus_pct": 50},
                   description="Vulnerable enemies take an additional 25% damage.",
                   upgraded_description="Vulnerable enemies take an additional 50% damage."),
    lambda: _card("Dominate", 1, CardType.SKILL, TargetMode.SINGLE_ENEMY, fx_dominate,
                   values={"vulnerable": 1}, upgrade_values={"vulnerable": 2}, exhausts=True,
                   description="Apply 1 Vulnerable. Gain 1 Strength for each Vulnerable on the enemy. Exhaust.",
                   upgraded_description="Apply 2 Vulnerable. Gain 1 Strength for each Vulnerable on the enemy. Exhaust."),
    lambda: _card("Flame Barrier", 2, CardType.SKILL, TargetMode.SELF, fx_flame_barrier,
                   values={"block": 12, "thorns": 4}, upgrade_values={"block": 16, "thorns": 6},
                   description="Gain 12 Block. Whenever you are attacked this turn, deal 4 damage back.",
                   upgraded_description="Gain 16 Block. Whenever you are attacked this turn, deal 6 damage back."),
    lambda: _card("Grapple", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_grapple,
                   values={"damage": 7, "followup": 5}, upgrade_values={"damage": 9, "followup": 7},
                   description="Deal 7 damage. Whenever you gain Block this turn, deal 5 damage to the enemy.",
                   upgraded_description="Deal 9 damage. Whenever you gain Block this turn, deal 7 damage to the enemy."),
    lambda: _card("Hellraiser", 2, CardType.POWER, TargetMode.SELF, fx_hellraiser,
                   upgrade_cost=1,
                   description="Whenever you draw a card containing \"Strike\", it is played against a random enemy.",
                   upgraded_description="Whenever you draw a card containing \"Strike\", it is played against a random enemy."),
    lambda: _card("Howl from Beyond", 3, CardType.ATTACK, TargetMode.ALL_ENEMIES, fx_howl_from_beyond,
                   values={"damage": 18}, upgrade_values={"damage": 24},
                   description="Deal 18 damage to ALL enemies. At the end of your turn, if this is in your Exhaust Pile, play it.",
                   upgraded_description="Deal 24 damage to ALL enemies. At the end of your turn, if this is in your Exhaust Pile, play it."),
    lambda: _card("Juggling", 1, CardType.POWER, TargetMode.SELF, fx_juggling,
                   innate_on_upgrade=True,
                   description="Add a copy of the third Attack you play each turn into your Hand.",
                   upgraded_description="Innate. Add a copy of the third Attack you play each turn into your Hand."),
    lambda: _card("Mangle", 3, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_mangle,
                   values={"damage": 20, "strength_loss": 10},
                   upgrade_values={"damage": 26, "strength_loss": 15},
                   description="Deal 20 damage. Enemy loses 10 Strength this turn.",
                   upgraded_description="Deal 26 damage. Enemy loses 15 Strength this turn."),
    lambda: _card("Midnight", 12, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_plain_attack,
                   values={"damage": 60}, upgrade_values={"damage": 72},
                   dynamic_cost=_midnight_cost,
                   description="Deal 60 damage. Costs 1 less for each card Exhausted this combat by ANYONE.",
                   upgraded_description="Deal 72 damage. Costs 1 less for each card Exhausted this combat by ANYONE."),
    lambda: _card("One-Two Punch", 1, CardType.SKILL, TargetMode.SELF, fx_one_two_punch,
                   values={"replays": 1}, upgrade_values={"replays": 2},
                   description="This turn, your next Attack is played an extra time.",
                   upgraded_description="This turn, your next 2 Attacks are played an extra time."),
    lambda: _card("Primal Force", 0, CardType.SKILL, TargetMode.SELF, fx_primal_force,
                   description="Transform all Attacks in your Hand into Giant Rock.",
                   upgraded_description="Transform all Attacks in your Hand into Giant Rock+."),
    lambda: _card("Stampede", 2, CardType.POWER, TargetMode.SELF, fx_stampede,
                   upgrade_cost=1,
                   description="At the end of your turn, 1 random Attack in your Hand is played against a random enemy.",
                   upgraded_description="At the end of your turn, 1 random Attack in your Hand is played against a random enemy."),
    lambda: _card("Stoke", 1, CardType.SKILL, TargetMode.SELF, fx_stoke,
                   description="Exhaust your Hand. Add 1 random card into your Hand for each card Exhausted.",
                   upgraded_description="Exhaust your Hand. Add 1 random Upgraded card into your Hand for each card Exhausted."),
    lambda: _card("Stomp", 3, CardType.ATTACK, TargetMode.ALL_ENEMIES, fx_stomp,
                   values={"damage": 12}, upgrade_values={"damage": 15},
                   dynamic_cost=_stomp_cost,
                   description="Deal 12 damage to ALL enemies. Costs 1 less for each Attack played this turn.",
                   upgraded_description="Deal 15 damage to ALL enemies. Costs 1 less for each Attack played this turn."),
    lambda: _card("Unrelenting", 2, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_unrelenting,
                   values={"damage": 14}, upgrade_values={"damage": 20},
                   description="Deal 14 damage. The next Attack you play costs 0.",
                   upgraded_description="Deal 20 damage. The next Attack you play costs 0."),
    lambda: _card("Vicious", 1, CardType.POWER, TargetMode.SELF, fx_vicious,
                   values={"cards": 1}, upgrade_values={"cards": 2},
                   description="Whenever you apply Vulnerable, draw 1 card.",
                   upgraded_description="Whenever you apply Vulnerable, draw 2 cards."),
]


ANCIENT_CARDS_IRONCLAD: List[Callable[[], Card]] = [
    lambda: _card("Break", 1, CardType.ATTACK, TargetMode.SINGLE_ENEMY, fx_attack_vulnerable,
                   values={"damage": 20, "vulnerable": 5},
                   upgrade_values={"damage": 30, "vulnerable": 7},
                   description="Deal 20 damage. Apply 5 Vulnerable.",
                   upgraded_description="Deal 30 damage. Apply 7 Vulnerable."),
    lambda: _card("Corruption", 3, CardType.POWER, TargetMode.SELF, fx_corruption,
                   upgrade_cost=2,
                   description="Skills cost 0. Whenever you play a Skill, Exhaust it.",
                   upgraded_description="Skills cost 0. Whenever you play a Skill, Exhaust it."),
]


def make_ironclad_pool_deck() -> List[Card]:
    """One fresh copy of every ported real Ironclad card -- useful for testing/demoing the full ported..."""
    return [factory() for factory in CARD_POOL_IRONCLAD]


FACTORIES_BY_TYPE: Dict[CardType, List[Callable[[], Card]]] = {}


FACTORIES_BY_RARITY: Dict[str, List[Callable[[], Card]]] = {}


for _factory in CARD_POOL_IRONCLAD:
    _sample = _factory()
    FACTORIES_BY_TYPE.setdefault(_sample.card_type, []).append(_factory)
    FACTORIES_BY_RARITY.setdefault(_sample.rarity, []).append(_factory)


del _factory, _sample


def _assert_rarity_coverage():
    """Guard the 'unlisted == Uncommon' default in rarity_for_card()."""
    tiers = {r: len(v) for r, v in FACTORIES_BY_RARITY.items()}
    unexpected = set(tiers) - {"Common", "Uncommon", "Rare"}
    assert not unexpected, f"unexpected rarity tier in the card pool: {unexpected}"
    assert tiers.get("Common") == len(_COMMON_CARDS), (
        f"expected all {len(_COMMON_CARDS)} Common cards in the pool, found {tiers.get('Common')}")


_assert_rarity_coverage()


def _all_card_names() -> List[str]:
    names = set()
    for pool in (CARD_POOL_IRONCLAD, ANCIENT_CARDS_IRONCLAD, COLORLESS_POOL,
                 ANCIENT_COLORLESS, CURSE_POOL):
        names |= {f().name for f in pool}
    names |= {mk().name for mk in STATUS_CARDS}
    names |= {c.name for c in make_starter_deck()}
    for fn in (make_wound, make_infection, make_dazed, make_slimed, make_beckon,
               make_toxic, make_burn, make_frantic_escape, make_giant_rock,
               make_wither):
        names.add(fn().name)
    return sorted(names)


CARD_IDS: Dict[str, int] = {name: i for i, name in enumerate(_all_card_names())}


TOTAL_CARD_IDS = len(CARD_IDS)


def card_id(card: "Card") -> int:
    """Stable id for a card, or -1 if it is not a known printing. -1 rather than a KeyError because a..."""
    return CARD_IDS.get(card.name, -1)
