"""What an upgrade changes, per card: attribute name -> its upgraded value.

One table rather than a line in each of 191 card files. A card reads its
numbers off its own constants, so Card.apply_upgrade just sets them on the
instance; "properties" holds the flag changes (Innate, loses Exhaust).

Upgrades are combat-scoped: piles are rebuilt from the deck each fight, so
there is nothing to revert.
"""

UPGRADES = {
    "aggression":            {'properties': {'innate': True}},
    "anger":                 {'DAMAGE': 8},
    "anointed":              {'properties': {'retain': True}},
    "apotheosis":            {'cost': 1},
    "apparition":            {'properties': {'ethereal': False}},
    "ashen_strike":          {'EXTRA_PER_EXHAUSTED': 4},
    "automation":            {'cost': 0},
    "barricade":             {'cost': 2},
    "bash":                  {'DAMAGE': 10, 'VULNERABLE': 3},
    "battle_trance":         {'CARDS': 4},
    "beacon_of_hope":        {'properties': {'innate': True}},
    "beat_down":             {'COUNT': 4},
    "believe_in_you":        {'ENERGY': 3},
    "blaze":                 {'STRENGTH': 7},
    "blood_wall":            {'BLOCK': 20},
    "bloodletting":          {'ENERGY': 3},
    "bludgeon":              {'DAMAGE': 42},
    "body_slam":             {'cost': 0},
    "bolas":                 {'DAMAGE': 4},
    "brand":                 {'STRENGTH': 2},
    "break":                 {'DAMAGE': 30, 'VULNERABLE': 7},
    "breakthrough":          {'DAMAGE': 13},
    "brightest_flame":       {'CARDS': 3, 'ENERGY': 3},
    "bully":                 {'EXTRA_PER_VULNERABLE': 3},
    "burning_pact":          {'CARDS': 3},
    "byrd_swoop":            {'DAMAGE': 18},
    "calamity":              {'cost': 2},
    "caltrops":              {'THORNS': 5},
    "catastrophe":           {'COUNT': 3},
    "cinder":                {'DAMAGE': 24},
    "clash":                 {'DAMAGE': 18},
    "colossus":              {'BLOCK': 7},
    "conflagration":         {'ROUNDS': 5},
    "coordinate":            {'STRENGTH': 8},
    "corruption":            {'cost': 2},
    "crimson_mantle":        {'AMOUNT': 10},
    "dark_embrace":          {'cost': 1},
    "dark_shackles":         {'STRENGTH_LOSS': 15},
    "defend":                {'BLOCK': 8},
    "demon_form":            {'AMOUNT': 4},
    "demonic_shield":        {'properties': {'exhaust': False}},
    "discovery":             {'properties': {'exhaust': False}},
    "dismantle":             {'DAMAGE': 10},
    "distraction":           {'cost': 0},
    "dominate":              {'VULNERABLE': 2},
    "dramatic_entrance":     {'DAMAGE': 15},
    "drum_of_battle":        {'ENERGY': 3},
    "dual_wield":            {'COPIES': 2},
    "entropy":               {'properties': {'innate': True}},
    "equilibrium":           {'BLOCK': 16},
    "eternal_armor":         {'PLATING': 12},
    "evil_eye":              {'BLOCK': 11},
    "expect_a_fight":        {'BLOCK': 16, 'EXTRA_PER_STRENGTH': 8},
    "exterminate":           {'DAMAGE': 4},
    "fasten":                {'BLOCK': 6},
    "feed":                  {'DAMAGE': 12, 'MAX_HP': 4},
    "feeding_frenzy":        {'STRENGTH': 7},
    "feel_no_pain":          {'AMOUNT': 4},
    "fiend_fire":            {'DAMAGE_PER_CARD': 10},
    "fight_me":              {'DAMAGE': 6, 'STRENGTH': 4},
    "finesse":               {'BLOCK': 7},
    "fisticuffs":            {'DAMAGE': 9},
    "flame_barrier":         {'BLOCK': 16, 'AMOUNT': 6},
    "flash_of_steel":        {'DAMAGE': 8},
    "forgotten_ritual":      {'ENERGY': 4},
    "gang_up":               {'PER_ALLY': 7},
    "gold_axe":              {'properties': {'retain': True}},
    "hand_of_greed":         {'DAMAGE': 25},
    "havoc":                 {'cost': 0},
    "headbutt":              {'DAMAGE': 12},
    "hello_world":           {'properties': {'innate': True}},
    "hellraiser":            {'cost': 1},
    "hemokinesis":           {'DAMAGE': 20},
    "hidden_gem":            {'REPLAY': 3},
    "howl_from_beyond":      {'DAMAGE': 24},
    "huddle_up":             {'CARDS': 3},
    "impatience":            {'CARDS': 3},
    "impervious":            {'BLOCK': 40},
    "inferno":               {'AMOUNT': 9},
    "inflame":               {'STRENGTH': 3},
    "intercept":             {'BLOCK': 13},
    "iron_wave":             {'BLOCK': 7, 'DAMAGE': 7},
    "jack_of_all_trades":    {'COUNT': 2},
    "jackpot":               {'DAMAGE': 30},
    "juggernaut":            {'AMOUNT': 7},
    "juggling":              {'properties': {'innate': True}},
    "lift":                  {'BLOCK': 16},
    "mangle":                {'DAMAGE': 26, 'STRENGTH_LOSS': 15},
    "master_of_strategy":    {'CARDS': 4},
    "maul":                  {'BONUS': 3, 'DAMAGE': 6},
    "mayhem":                {'cost': 1},
    "metamorphosis":         {'COUNT': 5},
    "midnight":              {'DAMAGE': 72},
    "mimic":                 {'properties': {'exhaust': False}},
    "molten_fist":           {'DAMAGE': 14},
    "neows_fury":            {'COUNT': 3, 'DAMAGE': 14},
    "nostalgia":             {'cost': 0},
    "not_yet":               {'HEAL': 13},
    "offering":              {'CARDS': 5},
    "omnislice":             {'DAMAGE': 11},
    "one_two_punch":         {'REPLAYS': 2},
    "outrage":               {'DAMAGE': 13},
    "pacts_end":             {'DAMAGE': 24},
    "panic_button":          {'BLOCK': 40},
    "peck":                  {'HITS': 4},
    "perfected_strike":      {'EXTRA_PER_STRIKE': 3},
    "pillage":               {'DAMAGE': 9},
    "pommel_strike":         {'CARDS': 2, 'DAMAGE': 10},
    "prep_time":             {'VIGOR': 6},
    "production":            {'ENERGY': 3},
    "prolong":               {'properties': {'exhaust': False}},
    "prowess":               {'AMOUNT': 2},
    "purity":                {'COUNT': 5},
    "pyre":                  {'AMOUNT': 2},
    "rage":                  {'AMOUNT': 5},
    "rally":                 {'BLOCK': 17},
    "rampage":               {'INCREASE': 10},
    "rebound":               {'DAMAGE': 12},
    "rend":                  {'DAMAGE': 12, 'PER_DEBUFF': 8},
    "restlessness":          {'CARDS': 3, 'ENERGY': 3},
    "rip_and_tear":          {'DAMAGE': 9},
    "rolling_boulder":       {'DAMAGE': 10},
    "rupture":               {'AMOUNT': 2},
    "salvo":                 {'DAMAGE': 16},
    "scrawl":                {'properties': {'retain': True}},
    "second_wind":           {'BLOCK_PER_CARD': 7},
    "seeker_strike":         {'DAMAGE': 12},
    "setup_strike":          {'DAMAGE': 9, 'STRENGTH': 4},
    "shockwave":             {'AMOUNT': 5},
    "shrug_it_off":          {'BLOCK': 11},
    "spite":                 {'HITS_IF_HURT': 3},
    "squash":                {'DAMAGE': 12, 'VULNERABLE': 3},
    "stack":                 {'BONUS': 3},
    "stampede":              {'cost': 1},
    "stomp":                 {'DAMAGE': 15},
    "stone_armor":           {'PLATING': 6},
    "stratagem":             {'cost': 0},
    "strike":                {'DAMAGE': 9},
    "sword_boomerang":       {'HITS': 4},
    "tag_team":              {'DAMAGE': 15},
    "tank":                  {'cost': 0},
    "taunt":                 {'BLOCK': 7, 'VULNERABLE': 2},
    "tear_asunder":          {'DAMAGE': 7},
    "the_gambit":            {'BLOCK': 75},
    "thinking_ahead":        {'properties': {'exhaust': False}},
    "thrash":                {'DAMAGE': 6},
    "thrumming_hatchet":     {'DAMAGE': 14},
    "thunderclap":           {'DAMAGE': 7},
    "toric_toughness":       {'BLOCK': 7},
    "tremble":               {'VULNERABLE': 4},
    "true_grit":             {'BLOCK': 9},
    "twin_strike":           {'DAMAGE': 7},
    "ultimate_defend":       {'BLOCK': 15},
    "ultimate_strike":       {'DAMAGE': 20},
    "unrelenting":           {'DAMAGE': 20},
    "uppercut":              {'VULNERABLE': 2, 'WEAK': 2},
    "vicious":               {'AMOUNT': 2},
    "volley":                {'DAMAGE': 14},
    "whirlwind":             {'DAMAGE': 8},
    "whistle":               {'DAMAGE': 44},
    "wish":                  {'properties': {'retain': True}},
}


def upgrade_for(card_id):
    """What upgrading this card changes.

    Empty for a card that prints the same either way, and for the six whose
    upgraded number lives on a status rather than on the card:
    cruelty, knockdown, outmaneuver, panache, relax, the_bomb.
    """
    return UPGRADES.get(card_id, {})
